<!-- Try Catch -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Promise</title>
  </head>
  <body>
    <script>
      const ff = async () => {
        try {
          await new Promise((resolve, reject) => {
            console.log(111);
            setTimeout(function () {
              console.log(222);
              reject("bbbb");
            }, 500 + Math.random() * 1000);
            console.log(333);
          });
        } catch (error) {
          console.log("error: ", error);
        }
      };

      ff();
    </script>
  </body>
</html>
